In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
### Problem 1-1
lst = [2, 5, 8, 9]
numA = torch.tensor(lst)
print(numA)
print("shape: {}, device: {}, dtype: {}".format(numA.shape, numA.device, numA.dtype))

tensor([2, 5, 8, 9])
shape: torch.Size([4]), device: cpu, dtype: torch.int64


In [3]:
### Problem 1-2
numE = np.array(numA)
print (numE)

[2 5 8 9]


In [4]:
### Problem 2-1
numB = torch.zeros((4, 5))
numB = numB + 2
numB

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

In [5]:
### Problem 2-2
numC = torch.ones((4, 5))
numD = numB + numC
numD

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

In [6]:
### Problem 3-1
numF = np.random.randn(20).reshape((5, 4))
numG = torch.from_numpy(numF)
numG

tensor([[ 0.1848, -0.3165,  0.7548, -0.9935],
        [ 0.6102,  0.7002, -0.5710, -1.1957],
        [-0.5787,  1.6947,  0.2909, -0.0339],
        [-1.0902,  0.7952,  0.1263, -0.9295],
        [ 0.8460,  0.6526,  0.1263, -0.6826]], dtype=torch.float64)

In [7]:
### Problem 3-2
numH = torch.randn_like(numG)
numH = torch.matmul(numG, numH.T)
numH

tensor([[ 0.2098,  2.1778, -1.2210, -0.2956, -0.1750],
        [-1.5696,  1.2696, -0.7864, -1.4668,  2.0199],
        [-1.2547,  3.9220,  1.1555, -4.9987,  0.4346],
        [-0.6413,  3.3588,  0.1766, -3.3834,  0.7570],
        [-1.0999,  1.8789, -0.6211, -1.5588,  0.8855]], dtype=torch.float64)

In [8]:
### Problem 4
X = torch.tensor([1, 2, 3, 4, 5], dtype = torch.float32)
W = torch.randn (5, dtype = torch.float32)
b = torch.randn (1, dtype = torch.float32)
H = torch.matmul(X, W) + b
Y = torch.sigmoid(H)
print ("X:", X)
print ("W:", W)
print ("b:", b)
print ("H:", H)
print ("Y:", Y)

X: tensor([1., 2., 3., 4., 5.])
W: tensor([-1.4714,  0.0670, -0.1134, -0.8371,  0.2535])
b: tensor([-1.0625])
H: tensor([-4.8211])
Y: tensor([0.0080])


In [9]:
### Problem 5
X = torch.tensor([1, 2, 3, 4, 5], dtype = torch.float32)
W = torch.randn ((5, 3), dtype = torch.float32)
b = torch.randn (3, dtype = torch.float32)
H = torch.matmul(X, W) + b
H = torch.sigmoid(H)
print ("X:", X)
print ("W:", W)
print ("b:", b)
print ("H:", H)

X: tensor([1., 2., 3., 4., 5.])
W: tensor([[ 1.4851,  0.5083,  0.0996],
        [-0.9396,  0.2929,  0.2804],
        [-1.1997, -0.5109, -0.1780],
        [-0.9841,  0.6139, -0.2622],
        [-1.2287, -0.6026, -0.6712]])
b: tensor([-0.4060,  0.1037,  0.4520])
H: tensor([5.1498e-07, 2.9058e-01, 2.1327e-02])


In [10]:
### Problem 6
X = torch.tensor([1, 2, 3, 4, 5], dtype = torch.float32)
W = torch.randn ((3, 3), dtype = torch.float32)
b = torch.randn (3, dtype = torch.float32)
Y = torch.matmul(H, W) + b
a = torch.nn.Softmax()
Y = a(Y)						# activation function
print ("X:", X)
print ("W:", W)
print ("b:", b)
print ("Y:", Y)

X: tensor([1., 2., 3., 4., 5.])
W: tensor([[ 0.8052,  1.7332,  0.9247],
        [-1.0615,  1.8964, -0.6034],
        [-0.2892,  1.3633, -0.9021]])
b: tensor([-0.7367, -0.3285,  3.2190])
Y: tensor([0.0157, 0.0579, 0.9264])


/Users/e0503474/.brew/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  import sys
